### ISSUE TITLE
Malfunction with summaryComponent

### ISSUE THREAD

**Issue by Marco-Costa** [ivylabs/IvyDC#41]
I'm building a dashboard where I am using several 'summaryComponent'.

The result I'm getting is all the same, no matter if value 1 is higher or lower than value 2.  The arrow doesn't change. 

here a picture illustrating the situation: 
http://oi60.tinypic.com/mm7x3a.jpg

what to do ?

**Comment by latinojoel** [comment]
Hi @Marco-Costa,

I think you don't have the latest version of IvyDC. If you have, make sure the numbers you're getting are numeric and not string types (as you're doing a SQL query maybe in the database the numbers are varchar types). I did a test similar based on your image and it's working for me. Check the images.

![firefox_screenshot_2015-02-07t11-58-45 629z](https://cloud.githubusercontent.com/assets/2965215/6092028/2c80abb0-aec1-11e4-9c38-ee17bd893967.png)
![firefox_screenshot_2015-02-07t11-59-11 353z](https://cloud.githubusercontent.com/assets/2965215/6092029/2c82b7c0-aec1-11e4-9d8d-db4119c52f6d.png)

Cheers.

**Comment by Marco-Costa** [comment]
Thank you latinojoel for your reply,

I do have the latest version of IvyDC, and I do have the values stored on my DB as numeric. 
By looking at the second image from your reply I found the error. 

On my datasource I was only getting two values, when I need three. 

Problem Solved, Thank you
