### ISSUE TITLE
Error with Pyramid and Funnel on tools > Ivy Dashboard Components

### ISSUE THREAD

**Issue by owendb** [ivylabs/IvyDC#42]
### Using : 

IvyDC - Ivy Dashboard Components 0.0.5 Stable from Marketplace
Pentaho EE 5.3.0.0.213

### Errors : 
>Error processing component (SAMPLE_FUNNEL_1)
>Error processing component (SAMPLE_PYRAMID_1)

If you let me know which log file to look at I can see if there's anything in there.

**Comment by latinojoel** [comment]
Hi @owendb,

Thanks to report this issue. Please, check the fixes in the 0.0.6 branch of this project. The 0.0.6 will be the new version of IvyDC, we're just planning publishing the new version based in the number of issues solved or new components.

Cheers
Joel

**Comment by owendb** [comment]
Awesome, will wait for the update in marketplace.

Cheers.
Owen.
