### ISSUE TITLE
Error with jQVectorMapComponent > Ivy Dashboard Components 

### ISSUE THREAD

**Issue by Marco-Costa** [ivylabs/IvyDC#43]
After updating to  15.02.26 (Stable) my vector map stop working

I still can see the map, and when I move the mouse over the zones still can see the value from that zone, but I'm not getting the map filled with colours.

![vector map](https://cloud.githubusercontent.com/assets/10886357/6623364/6d1b49d6-c8da-11e4-8c62-e4ee6f776e7e.PNG)

**Comment by latinojoel** [comment]
Hi @Marco-Costa,

Please check the 0.0.6 branch (is fixed) will be the new version in the marketplace.

Cheers
Joel
