### ISSUE TITLE
Pyramid Chart component > Columns title swapped 

### ISSUE THREAD

**Issue by Marco-Costa** [ivylabs/IvyDC#44]
On Pyramid Chart component the title of each column is swapped  with the title of the other. 

i mean:
the title of the left column appears as the title of the right column and vice versa.

**Comment by latinojoel** [comment]
Hi @Marco-Costa,

This isn't a issue is working fine in the samples dashboards. You can edit the main dashboard using the following [url](http://localhost:8080/pentaho/plugin/IvyDC/api/main?mode=edit), for me looks fine.

Cheers!
